### ISSUE TITLE
apple-gcc42 error with homebrew update

### ISSUE THREAD

**Issue by joeheald85** [Homebrew/homebrew-dupes#542]
After doing a 'brew update', the output for 'brew info apple-gcc42' includes an error. The error also prevents a 'brew uninstall apple-gcc42'. See the output below prior to and after running 'brew update'..

```
$ brew info apple-gcc42
homebrew/dupes/apple-gcc42: stable 4.2.1-5666.3
GNU compiler collection
http://r.research.att.com/tools/
/usr/local/Cellar/apple-gcc42/4.2.1-5666.3 (104 files, 75M) *
  Built from source
From: https://github.com/Homebrew/homebrew-dupes/blob/master/apple-gcc42.rb
==> Options
--with-gfortran-symlink
	Provide gfortran symlinks
==> Caveats
NOTE:
This formula provides components that were removed from XCode in the 4.2
release. There is no reason to install this formula if you are using a
version of XCode prior to 4.2.

This formula contains compilers built from Apple's GCC sources, build
5666.3, available from:

  http://opensource.apple.com/tarballs/gcc

All compilers have a `-4.2` suffix. A GFortran compiler is also included.
```

Then the brew update...

```
$ brew update
Updated Homebrew from e4e15f3c to eab1242b.

Updated 2 taps (homebrew/dupes, homebrew/versions).
==> New Formulae
artifactory-cli-go            cpprestsdk                    elm                           gowsdl                        jerasure                      moz-git-tools                 pod2man                       swift                         zimg                        
cdiff                         cromwell                      gdm                           homebrew/versions/kettle54    joshua                        mpv                           powerline                     taylor                        zita-convolver              
clog                          digitemp                      gf-complete                   homebrew/versions/kibana41    liberasurecode                mvtools                       scour                         vapoursynth                 
corectl                       dupseek                       git-secrets                   homebrew/versions/kibana42    libilbc                       ploticus                      shibboleth-sp                 weboob                      
==> Updated Formulae
abcde                         ccextractor                   flow                          haskell-stack                 libcdr                        makensis                      perl                          ruby-build                    taglib                      
abcl                          cd-discid                     fluent-bit                    highlight                     libetonyek                    mal4s                         pgbadger                      ruby-install                  texmath                     
agda                          cgrep                         ford                          highlighting-kate             libev                         mbedtls                       pgroonga                      saltstack                     the_platinum_searcher       
algol68g                      cless                         freeipmi                      homebrew/dupes/ncurses        libgetdata                    mesos                         podofo                        sdl2_gfx                      twemcache                   
ammonite-repl                 commonmark                    freetds ✔                     homebrew/dupes/whois          libhttpserver                 mighttpd2                     poppler                       serd                          udunits                     
ansible                       cryptol                       gegl                          homebrew/versions/node4-lts   libmicrohttpd                 minbif                        postgrest                     sfcgal ✔                      uru                         
appscale-tools                cryptopp                      geoserver                     htop-osx                      libmtp                        nghttp2                       primesieve                    shadowsocks-libev             userspace-rcu               
arangodb                      crystal-lang                  ghi                           idris                         libpng ✔                      nifi                          purescript                    shellcheck                    vim                         
argyll-cms                    d-bus                         git-annex                     imagemagick ✔                 libraw                        nomad                         pyenv                         skinny                        vramsteg                    
aurora-cli                    darcs                         git-extras                    internetarchive               librevenge                    nss                           pyenv-virtualenv              sngrep                        wine                        
autoconf-archive              dbxml                         glide                         ircii                         librsync                      ntl                           qt                            sord                          wireshark                   
awscli                        dialog                        gnupg                         iso-codes                     libsodium                     nvm                           rabbitmq                      sourcekitten                  wxmac                       
babl                          diff-pdf                      gnuradio                      jailkit                       libwpg                        ode                           rabbitmq-c                    spoof-mac                     x265                        
bash-git-prompt               docker-machine                godep                         jenkins                       lilv                          ola                           rakudo-star                   sqlcipher                     xapian                      
bigdata                       dos2unix                      goffice                       kettle                        link-grammar                  p7zip                         rancher-compose               squid                         xmlto                       
blink1                        duplicity                     gom                           keybase                       lldpd                         pandoc                        rbenv                         sslscan                       xqilla                      
boot-clj                      epic5                         gphoto2                       kibana                        logentries                    pandoc-citeproc               rdiff-backup                  subliminal                    yap                         
burp                          erlang                        gradle                        knot                          logstalgia                    parallel                      redis                         subversion ✔                  youtube-dl                  
cairo ✔                       exercism                      graphicsmagick                kotlin-compiler               logtalk                       passenger                     rethinkdb                     swiftgen                      znc                         
cake                          f3                            h2o                           lastpass-cli                  luvit                         pcsc-lite                     rrdtool                       swiftlint                   
cassandra                     ffmpeg                        haproxy                       latex2html                    macvim                        pdf2htmlex                    ruby                          syncthing                   
==> Deleted Formulae
rbenv-gem-rehash
```

then the same 'brew info apple-gcc42' call...

```
$ brew info apple-gcc42
homebrew/dupes/apple-gcc42: stable 4.2.1-5666.3
GNU compiler collection
http://r.research.att.com/tools/
Error: No such file or directory - /usr/local/Cellar/apple-gcc42/4.2.1-5666.3/libexec/gcc/i686-apple-darwin11/4.2.1/as
```

**Comment by mikemcquaid** [comment]
@joeheald85 Please run `brew info apple-gcc42 --debug` and paste the output, thanks!

**Comment by DomT4** [comment]
^
```
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-dupes/apple-gcc42.rb
homebrew/dupes/apple-gcc42: stable 4.2.1-5666.3
GNU compiler collection
http://r.research.att.com/tools/
Error: No such file or directory - /usr/local/Cellar/apple-gcc42/4.2.1-5666.3/libexec/gcc/i686-apple-darwin11/4.2.1/as
/usr/local/Library/Homebrew/extend/pathname.rb:35:in `size'
/usr/local/Library/Homebrew/extend/pathname.rb:35:in `size'
/usr/local/Library/Homebrew/extend/pathname.rb:35:in `block in compute_disk_usage'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `find'
/usr/local/Library/Homebrew/extend/pathname.rb:32:in `compute_disk_usage'
/usr/local/Library/Homebrew/extend/pathname.rb:21:in `abv'
/usr/local/Library/Homebrew/keg.rb:134:in `abv'
/usr/local/Library/Homebrew/cmd/info.rb:113:in `block in info_formula'
/usr/local/Library/Homebrew/cmd/info.rb:112:in `each'
/usr/local/Library/Homebrew/cmd/info.rb:112:in `info_formula'
/usr/local/Library/Homebrew/cmd/info.rb:35:in `block in print_info'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `each'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `each_with_index'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `print_info'
/usr/local/Library/Homebrew/cmd/info.rb:18:in `info'
/usr/local/Library/brew.rb:143:in `<main>'
```
